In [1]:
'''
Excel :

1.table - rows and columns
2.Add any two rows
3.Merge
4.Pivot tables

'''


import pandas as pd

In [2]:
pd.__version__

'1.5.3'

In [3]:
'''
SERIES
'''
#converting a list to pandas series
df = pd.Series([0.25,0.5,0.75,1.0])
df

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
#pandas series to numpy array
df.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
df[0] #indexing

0.25

In [6]:
# own indexes
df = pd.Series([0.25,0.5,0.75,1.0],index = ['a','b','c','d'])
df

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
df['a']

0.25

In [8]:
#Converting a dictionary to pandas series
population = {'AP':1000,'TS':800,'TN':6700,'KA':3400}

df = pd.Series(population)
df

AP    1000
TS     800
TN    6700
KA    3400
dtype: int64

In [9]:
df[1:]

TS     800
TN    6700
KA    3400
dtype: int64

In [10]:
df[1:3]

TS     800
TN    6700
dtype: int64

In [11]:
df['TS':]

TS     800
TN    6700
KA    3400
dtype: int64

In [12]:
df['TS':'TN']

TS     800
TN    6700
dtype: int64

In [13]:
ram = 10

In [14]:
population = [1000,800,6700,3400]
area = [100,8,15,25]
state_name = ['AP','TS','TN','KA']

#dataframe
state = pd.DataFrame({'state_name':state_name,'population':population,'area':area})
state

state_name  population  area
0         AP        1000   100
1         TS         800     8
2         TN        6700    15
3         KA        3400    25

In [15]:
population = {'AP':1000,'TS':800,'TN':6700,'KA':3400}
area = {'AP':100,'TS':8,'TN':15,'KA':25}

#dataframe
state = pd.DataFrame({'population':population,'area':area})
state

population  area
AP        1000   100
TS         800     8
TN        6700    15
KA        3400    25

In [16]:
state = state.reset_index()
state.columns = ['state_name','population','area']
state

state_name  population  area
0         AP        1000   100
1         TS         800     8
2         TN        6700    15
3         KA        3400    25

In [17]:
state.values # matrix of shape 4x2

array([['AP', 1000, 100],
       ['TS', 800, 8],
       ['TN', 6700, 15],
       ['KA', 3400, 25]], dtype=object)

In [18]:
#to get the index of the dataframe
state.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
state.columns #to find the column names

Index(['state_name', 'population', 'area'], dtype='object')

In [20]:
#to get a specific column
state['area']

0    100
1      8
2     15
3     25
Name: area, dtype: int64

In [21]:
## second scenario of conveting into a pandas dataframe from a dictionary
data = [{'a':i,'b':2*i} for i in range(10)] #list of dictinaries
data

[{'a': 0, 'b': 0},
 {'a': 1, 'b': 2},
 {'a': 2, 'b': 4},
 {'a': 3, 'b': 6},
 {'a': 4, 'b': 8},
 {'a': 5, 'b': 10},
 {'a': 6, 'b': 12},
 {'a': 7, 'b': 14},
 {'a': 8, 'b': 16},
 {'a': 9, 'b': 18}]

In [22]:
pd.DataFrame(data)

a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
6  6  12
7  7  14
8  8  16
9  9  18

In [23]:
data = [{'a':10,'b':20},{'c':30,'d':40}] #NaN - Not a number
pd.DataFrame(data)

a     b     c     d
0  10.0  20.0   NaN   NaN
1   NaN   NaN  30.0  40.0

In [24]:
'''
Homework : Create a pandas dataframw with first column as evennumbers between 1 to 100 and second column as odd numbers between 1 to 100
'''

'\nHomework : Create a pandas dataframw with first column as evennumbers between 1 to 100 and second column as odd numbers between 1 to 100\n'

In [25]:
#numpy matrix to pandas dataframe
import numpy as np
array = np.random.random((3,2))
array

array([[0.87092524, 0.70615652],
       [0.86658216, 0.77330748],
       [0.61347381, 0.4780846 ]])

In [26]:
pd.DataFrame(array,columns=['a','b'],index=['c','d','e'])

a         b
c  0.870925  0.706157
d  0.866582  0.773307
e  0.613474  0.478085

In [27]:
pd.DataFrame(np.ones((4,5)),columns=['a','b','c','d','e'],index=['a','b','c','d'])

a    b    c    d    e
a  1.0  1.0  1.0  1.0  1.0
b  1.0  1.0  1.0  1.0  1.0
c  1.0  1.0  1.0  1.0  1.0
d  1.0  1.0  1.0  1.0  1.0

In [28]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
df = pd.Series(arr,index=['a','b','c','d','e'])

In [30]:
df

a     1.00
b     3.25
c     5.50
d     7.75
e    10.00
dtype: float64

In [31]:
df['b']

3.25

In [32]:
df['b'] = 12

In [33]:
df

a     1.00
b    12.00
c     5.50
d     7.75
e    10.00
dtype: float64

In [34]:
df['a':'c']

a     1.0
b    12.0
c     5.5
dtype: float64

In [35]:
df[0:3]

a     1.0
b    12.0
c     5.5
dtype: float64

In [36]:
df

a     1.00
b    12.00
c     5.50
d     7.75
e    10.00
dtype: float64

In [37]:
df[df > 6]

b    12.00
d     7.75
e    10.00
dtype: float64

In [38]:
df[(df > 6) & (df < 10)]

d    7.75
dtype: float64

In [39]:
(df > 6) & (df < 10)

a    False
b    False
c    False
d     True
e    False
dtype: bool

In [40]:

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

In [41]:
data = pd.DataFrame({'area':area,'population':pop})

In [42]:
data

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [43]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
#it is for a dataframe -- iloc,loc
data.iloc[0]

area            423967
population    38332521
Name: California, dtype: int64

In [45]:
data.loc['California']

area            423967
population    38332521
Name: California, dtype: int64

In [46]:
data

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [47]:
data['density'] = data['population']/data['area']

In [48]:
data

area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [49]:
data.T #transpose of the data

California         Texas      New York       Florida  \
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
area        1.499950e+05  
population  1.288214e+07  
density     8.588376e+01

In [50]:
data

area  population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [51]:
data.iloc[:3][['area','density']]

area     density
California  423967   90.413926
Texas       695662   38.018740
New York    141297  139.076746

In [52]:
data.iloc[0:3,:2]

area  population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [53]:
marks = pd.DataFrame({'mathmarks':[10,20,30,40,50],'socialmarks':[20,40,50,80,90],'sciencemarks':[70,30,70,10,90]},index=['Ram','Rahul','Rohit','Kohli','Jadeja'])
marks

mathmarks  socialmarks  sciencemarks
Ram            10           20            70
Rahul          20           40            30
Rohit          30           50            70
Kohli          40           80            10
Jadeja         50           90            90

In [54]:
marks.loc['Jadeja']

mathmarks       50
socialmarks     90
sciencemarks    90
Name: Jadeja, dtype: int64

In [55]:
marks

mathmarks  socialmarks  sciencemarks
Ram            10           20            70
Rahul          20           40            30
Rohit          30           50            70
Kohli          40           80            10
Jadeja         50           90            90

In [56]:
marks[marks['sciencemarks'] > 20]

mathmarks  socialmarks  sciencemarks
Ram            10           20            70
Rahul          20           40            30
Rohit          30           50            70
Jadeja         50           90            90

In [57]:
marks[(marks['sciencemarks'] > 20)&(marks['socialmarks'] > 40)]

mathmarks  socialmarks  sciencemarks
Rohit          30           50            70
Jadeja         50           90            90

## Operations

In [58]:
## Random state
np.random.seed(99)
np.random.randint(0,10,8)

array([1, 3, 9, 8, 9, 8, 2, 4])

In [59]:
df = pd.DataFrame(np.random.randint(0,10,(3,4)),columns=['A','B','C','D'])

In [60]:
df

A  B  C  D
0  5  4  1  7
1  3  7  1  1
2  0  6  4  7

In [61]:
np.sin(df)

A         B         C         D
0 -0.958924 -0.756802  0.841471  0.656987
1  0.141120  0.656987  0.841471  0.841471
2  0.000000 -0.279415 -0.756802  0.656987

In [62]:
np.sin(df['A'])

0   -0.958924
1    0.141120
2    0.000000
Name: A, dtype: float64

In [63]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [64]:
#to count the nan values in each column
df.isnull().sum()

0    1
1    1
2    0
dtype: int64

In [65]:
# to remove na values
df.dropna() #default is axis = 0

0    1  2
1  2.0  3.0  5

In [66]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [67]:
#fill the nan
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [68]:
df.ffill()

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [69]:
df.bfill()

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [70]:
# fill with mean value
df.fillna(df.mean())
#df.fillna(value='')

0    1  2
0  1.0  3.5  2
1  2.0  3.0  5
2  1.5  4.0  6

## Hierarchial indexing

In [79]:
index = [('California', 2000),('California', 2001), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]#list of tuples

population = [33871648,37253956,18976457,19378102,20851820,25145561,26448193]

In [80]:
df = pd.Series(population,index=index)
df

(California, 2000)    33871648
(California, 2001)    37253956
(California, 2010)    18976457
(New York, 2000)      19378102
(New York, 2010)      20851820
(Texas, 2000)         25145561
(Texas, 2010)         26448193
dtype: int64

In [81]:
df[('California',2010)]

18976457

In [82]:
df[('California',2010):('Texas',2010)]

(California, 2010)    18976457
(New York, 2000)      19378102
(New York, 2010)      20851820
(Texas, 2000)         25145561
(Texas, 2010)         26448193
dtype: int64

In [85]:
# converting a multiindex to sereis - done
# converting a multiindex to pandas dataframe

'''
1. Mutiindex setup
2. Reindexing
'''

#Multiindex setup
print(index)
index = pd.MultiIndex.from_tuples(index) #from list of tuples we are converting into MultiIndex

#Reindexing
print(df)
df = df.reindex(index)
print(df)

MultiIndex([('California', 2000),
            ('California', 2001),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )
(California, 2000)    33871648
(California, 2001)    37253956
(California, 2010)    18976457
(New York, 2000)      19378102
(New York, 2010)      20851820
(Texas, 2000)         25145561
(Texas, 2010)         26448193
dtype: int64
California  2000    33871648
            2001    37253956
            2010    18976457
New York    2000    19378102
            2010    20851820
Texas       2000    25145561
            2010    26448193
dtype: int64


In [87]:
index = [('California', 2000),('California', 2001), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]#list of tuples

population = [33871648,37253956,18976457,19378102,20851820,25145561,26448193]

#we are converting this to series
df_series = pd.Series(population,index = index)
print(df_series)
index = pd.MultiIndex.from_tuples(index)
df_series = df_series.reindex(index)
print(df_series)

(California, 2000)    33871648
(California, 2001)    37253956
(California, 2010)    18976457
(New York, 2000)      19378102
(New York, 2010)      20851820
(Texas, 2000)         25145561
(Texas, 2010)         26448193
dtype: int64
California  2000    33871648
            2001    37253956
            2010    18976457
New York    2000    19378102
            2010    20851820
Texas       2000    25145561
            2010    26448193
dtype: int64


In [88]:
df_series

California  2000    33871648
            2001    37253956
            2010    18976457
New York    2000    19378102
            2010    20851820
Texas       2000    25145561
            2010    26448193
dtype: int64

In [90]:
# I want to convert index 2 into the column
pop = df_series.unstack()

In [91]:
pop

2000        2001        2010
California  33871648.0  37253956.0  18976457.0
New York    19378102.0         NaN  20851820.0
Texas       25145561.0         NaN  26448193.0

In [92]:
pop.stack() # convert from index to columns we use "unstack" or from column to index "stack"

California  2000    33871648.0
            2001    37253956.0
            2010    18976457.0
New York    2000    19378102.0
            2010    20851820.0
Texas       2000    25145561.0
            2010    26448193.0
dtype: float64

In [94]:
type(df_series)

pandas.core.series.Series

In [100]:
under18 = ['1234','2345','545345','23423423','23423423','1232131','234245']
pd.DataFrame({'population':df_series,'Under18_pop':under18})

population Under18_pop
California 2000    33871648        1234
           2001    37253956        2345
           2010    18976457      545345
New York   2000    19378102    23423423
           2010    20851820    23423423
Texas      2000    25145561     1232131
           2010    26448193      234245

In [101]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])

#from_product([[],[],[]])

In [103]:
index = pd.MultiIndex.from_product([['a','b'],[1,2],['c','d']],names=['year','visit','category'])
index

MultiIndex([('a', 1, 'c'),
            ('a', 1, 'd'),
            ('a', 2, 'c'),
            ('a', 2, 'd'),
            ('b', 1, 'c'),
            ('b', 1, 'd'),
            ('b', 2, 'c'),
            ('b', 2, 'd')],
           names=['year', 'visit', 'category'])

In [102]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [104]:
index = [(2013,1),(2013,2),(2014,1),(2014,2)]
pd.MultiIndex.from_tuples(index)

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           )

In [105]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]])

In [106]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           )

In [108]:
#row multiindex
row_index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])

#column Multiindex
col_index = pd.MultiIndex.from_product([['BOb','Ram','Ravi'],['HR','Temp']],names=['subject','type'])

In [110]:
row_index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [111]:
col_index

MultiIndex([( 'BOb',   'HR'),
            ( 'BOb', 'Temp'),
            ( 'Ram',   'HR'),
            ( 'Ram', 'Temp'),
            ('Ravi',   'HR'),
            ('Ravi', 'Temp')],
           names=['subject', 'type'])

In [113]:
data = np.random.randn(4,6) #4 mean, 6 standard deviation
data

array([[-0.11306921, -2.36783759, -0.16704943,  0.68539797,  0.02350011,
         0.45620128],
       [ 0.27049278, -1.43500814,  0.88281715, -0.58008166, -0.5015653 ,
         0.59095329],
       [-0.73161625,  0.26175546, -0.85579558, -0.18752591, -0.37348629,
        -0.46197097],
       [-0.8164661 , -0.0451233 ,  0.12132778,  0.92595278, -0.5738197 ,
         0.05270311]])

In [115]:
df = pd.DataFrame(data,index=row_index,columns=col_index)

In [116]:
df

subject          BOb                 Ram                Ravi          
type              HR      Temp        HR      Temp        HR      Temp
year visit                                                            
2013 1     -0.113069 -2.367838 -0.167049  0.685398  0.023500  0.456201
     2      0.270493 -1.435008  0.882817 -0.580082 -0.501565  0.590953
2014 1     -0.731616  0.261755 -0.855796 -0.187526 -0.373486 -0.461971
     2     -0.816466 -0.045123  0.121328  0.925953 -0.573820  0.052703

In [117]:
df.mean(level='year')

<ipython-input-117-f2b73c205805>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.mean(level='year')


subject       BOb                 Ram                Ravi          
type           HR      Temp        HR      Temp        HR      Temp
year                                                               
2013     0.078712 -1.901423  0.357884  0.052658 -0.239033  0.523577
2014    -0.774041  0.108316 -0.367234  0.369213 -0.473653 -0.204634

In [118]:
df.mean(level='visit')

<ipython-input-118-7879c00e2993>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.mean(level='visit')


subject       BOb                 Ram                Ravi          
type           HR      Temp        HR      Temp        HR      Temp
visit                                                              
1       -0.422343 -1.053041 -0.511423  0.248936 -0.174993 -0.002885
2       -0.272987 -0.740066  0.502072  0.172936 -0.537693  0.321828

In [119]:
df.mean(level='subject',axis=1)

<ipython-input-119-2657ffed54e4>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.mean(level='subject',axis=1)


subject          BOb       Ram      Ravi
year visit                              
2013 1     -1.240453  0.259174  0.239851
     2     -0.582258  0.151368  0.044694
2014 1     -0.234930 -0.521661 -0.417729
     2     -0.430795  0.523640 -0.260558

In [120]:
df.mean(level='type',axis=1)

<ipython-input-120-3c2acadbd598>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.mean(level='type',axis=1)


type              HR      Temp
year visit                    
2013 1     -0.085540 -0.408746
     2      0.217248 -0.474712
2014 1     -0.653633 -0.129247
     2     -0.422986  0.311178

In [ ]:
'''
Join, concatenate, merge
Groupby
Pivot tables
'''