In [1]:
'''
Excel :

1.table - rows and columns
2.Add any two rows
3.Merge
4.Pivot tables

'''


import pandas as pd

In [2]:
pd.__version__

'1.5.3'

In [3]:
'''
SERIES
'''
#converting a list to pandas series
df = pd.Series([0.25,0.5,0.75,1.0])
df

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
#pandas series to numpy array
df.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
df[0] #indexing

0.25

In [6]:
# own indexes
df = pd.Series([0.25,0.5,0.75,1.0],index = ['a','b','c','d'])
df

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
df['a']

0.25

In [10]:
#Converting a dictionary to pandas series
population = {'AP':1000,'TS':800,'TN':6700,'KA':3400}

df = pd.Series(population)
df

AP    1000
TS     800
TN    6700
KA    3400
dtype: int64

In [11]:
df[1:]

TS     800
TN    6700
KA    3400
dtype: int64

In [15]:
df[1:3]

TS     800
TN    6700
dtype: int64

In [12]:
df['TS':]

TS     800
TN    6700
KA    3400
dtype: int64

In [14]:
df['TS':'TN']

TS     800
TN    6700
dtype: int64

In [ ]:
ram = 10

In [22]:
population = [1000,800,6700,3400]
area = [100,8,15,25]
state_name = ['AP','TS','TN','KA']

#dataframe
state = pd.DataFrame({'state_name':state_name,'population':population,'area':area})
state

state_name  population  area
0         AP        1000   100
1         TS         800     8
2         TN        6700    15
3         KA        3400    25

In [28]:
population = {'AP':1000,'TS':800,'TN':6700,'KA':3400}
area = {'AP':100,'TS':8,'TN':15,'KA':25}

#dataframe
state = pd.DataFrame({'population':population,'area':area})
state

population  area
AP        1000   100
TS         800     8
TN        6700    15
KA        3400    25

In [29]:
state = state.reset_index()
state.columns = ['state_name','population','area']
state

state_name  population  area
0         AP        1000   100
1         TS         800     8
2         TN        6700    15
3         KA        3400    25

In [17]:
state.values # matrix of shape 4x2

array([[1000,  100],
       [ 800,    8],
       [6700,   15],
       [3400,   25]])

In [18]:
#to get the index of the dataframe
state.index

Index(['AP', 'TS', 'TN', 'KA'], dtype='object')

In [20]:
state.columns #to find the column names

Index(['population', 'area'], dtype='object')

In [21]:
#to get a specific column
state['area']

AP    100
TS      8
TN     15
KA     25
Name: area, dtype: int64

In [30]:
## second scenario of conveting into a pandas dataframe from a dictionary
data = [{'a':i,'b':2*i} for i in range(10)] #list of dictinaries
data

[{'a': 0, 'b': 0},
 {'a': 1, 'b': 2},
 {'a': 2, 'b': 4},
 {'a': 3, 'b': 6},
 {'a': 4, 'b': 8},
 {'a': 5, 'b': 10},
 {'a': 6, 'b': 12},
 {'a': 7, 'b': 14},
 {'a': 8, 'b': 16},
 {'a': 9, 'b': 18}]

In [31]:
pd.DataFrame(data)

a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
6  6  12
7  7  14
8  8  16
9  9  18

In [32]:
data = [{'a':10,'b':20},{'c':30,'d':40}] #NaN - Not a number
pd.DataFrame(data)

a     b     c     d
0  10.0  20.0   NaN   NaN
1   NaN   NaN  30.0  40.0

In [ ]:
'''
Homework : Create a pandas dataframw with first column as evennumbers between 1 to 100 and second column as odd numbers between 1 to 100
'''

In [33]:
#numpy matrix to pandas dataframe
import numpy as np
array = np.random.random((3,2))
array

array([[0.08572536, 0.72188469],
       [0.22373716, 0.84382827],
       [0.66806698, 0.82212263]])

In [35]:
pd.DataFrame(array,columns=['a','b'],index=['c','d','e'])

a         b
c  0.085725  0.721885
d  0.223737  0.843828
e  0.668067  0.822123